import { useCallback, useEffect, useState } from 'react';
import { Eye, Pencil, Plus, Search, Trash2, Wrench } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { equipmentService } from '../../services/equipment';
import { customersService } from '../../services/customers';
import type { Equipment } from '../../types/equipment';
import type { Customer } from '../../types/customer';
import { ApiError } from '../../services/api';
import { Card } from '../../components/ui/Card';
import { SearchInput } from '../../components/ui/SearchInput';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { Toast } from '../../components/ui/Toast';
import { EmptyState, ErrorState, Loading } from '../../components/ui/ResourceStates';

export function EquipmentList() {
  const location = useLocation(); const [items, setItems] = useState<Equipment[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [search, setSearch] = useState(''); const [customerId, setCustomerId] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Equipment | null>(null); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState((location.state as { message?: string } | null)?.message ?? '');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [equipmentResponse, customersResponse] = await Promise.all([equipmentService.list(customerId || undefined), customersService.list()]); setItems(equipmentResponse.equipment); setCustomers(customersResponse.customers); } catch { setError('Não foi possível carregar os equipamentos.'); } finally { setLoading(false); } }, [customerId]);
  useEffect(() => { void load(); }, [load]);
  const filtered = items.filter((item) => [item.type, item.brand ?? '', item.model ?? '', item.serialNumber ?? '', item.customer.name].some((value) => value.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  const remove = async () => { if (!selected) return; setDeleting(true); try { await equipmentService.remove(selected.id); setItems((current) => current.filter((item) => item.id !== selected.id)); setSelected(null); setToast('Equipamento excluído com sucesso.'); } catch (cause) { setToast(cause instanceof ApiError && cause.status === 409 ? 'Não é possível excluir este equipamento porque existem ordens de serviço vinculadas a ele.' : 'Não foi possível excluir este equipamento.'); } finally { setDeleting(false); } };
  return <div className="resource-page"><div className="page-intro"><div><p className="eyebrow">Ativos cadastrados</p><h2>Equipamentos</h2><p className="muted">Acompanhe os equipamentos dos seus clientes.</p></div><Link className="button button-primary" to="/equipment/new"><Plus size={17} /> Novo equipamento</Link></div><Card className="resource-card"><div className="resource-toolbar equipment-toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Buscar por tipo, marca, modelo ou série" /><label className="filter-select"><Search size={15} /><select value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">Todos os clientes</option>{customers.map((customer) => <option value={customer.id} key={customer.id}>{customer.name}</option>)}</select></label><span className="result-count">{filtered.length} {filtered.length === 1 ? 'equipamento' : 'equipamentos'}</span></div>{loading ? <Loading message="Carregando equipamentos..." /> : error ? <ErrorState message={error} actionLabel="Tentar novamente" onAction={() => void load()} /> : items.length === 0 ? <EmptyState title="Nenhum equipamento encontrado" message="Cadastre o primeiro equipamento para começar." actionLabel="Novo equipamento" to="/equipment/new" /> : filtered.length === 0 ? <div className="inline-empty"><Wrench size={20} /><p>Nenhum equipamento corresponde aos filtros.</p></div> : <div className="table-wrap"><table className="resource-table"><thead><tr><th>Equipamento</th><th>Cliente</th><th>Número de série</th><th>Ações</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><Link className="resource-name" to={`/equipment/${item.id}`}>{[item.brand, item.model].filter(Boolean).join(' ') || item.type}</Link><small className="table-subtext">{item.type}</small></td><td><Link className="subtle-link" to={`/customers/${item.customer.id}`}>{item.customer.name}</Link></td><td className="muted">{item.serialNumber || 'Não informado'}</td><td><div className="row-actions"><Link className="table-action" to={`/equipment/${item.id}`} aria-label="Ver equipamento"><Eye size={16} /></Link><Link className="table-action" to={`/equipment/${item.id}/edit`} aria-label="Editar equipamento"><Pencil size={16} /></Link><button className="table-action danger-action" type="button" onClick={() => setSelected(item)} aria-label="Excluir equipamento"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>}</Card><ConfirmDialog isOpen={selected !== null} title="Excluir equipamento?" message="Essa ação não poderá ser desfeita. Ordens de serviço vinculadas impedem a exclusão." isLoading={deleting} onCancel={() => setSelected(null)} onConfirm={() => void remove()} />{toast ? <Toast message={toast} onClose={() => setToast('')} /> : null}</div>;
}
