import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Edit3, Hash, Laptop, Tag, Trash2, UserRound } from 'lucide-react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { equipmentService } from '../../services/equipment';
import type { Equipment } from '../../types/equipment';
import { ApiError } from '../../services/api';
import { Card } from '../../components/ui/Card';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { Toast } from '../../components/ui/Toast';
import { ErrorState, Loading } from '../../components/ui/Feedback';

export function EquipmentDetails() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [item, setItem] = useState<Equipment | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState((location.state as { message?: string } | null)?.message ?? '');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItem((await equipmentService.get(id)).equipment); } catch (cause) { setError(cause instanceof ApiError && cause.status === 404 ? 'Equipamento não encontrado.' : 'Não foi possível carregar o equipamento.'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const remove = async () => { setDeleting(true); try { await equipmentService.remove(id); navigate('/equipment', { state: { message: 'Equipamento excluído com sucesso.' } }); } catch (cause) { setToast(cause instanceof ApiError && cause.status === 409 ? 'Não é possível excluir este equipamento porque existem ordens de serviço vinculadas a ele.' : 'Não foi possível excluir este equipamento.'); setConfirm(false); } finally { setDeleting(false); } };
  if (loading) return <Loading message="Carregando equipamento..." />; if (error || !item) return <ErrorState message={error || 'Equipamento não encontrado.'} actionLabel="Voltar" onAction={() => navigate('/equipment')} />;
  const title = [item.brand, item.model].filter(Boolean).join(' ') || item.type;
  return <div className="details-page"><Link className="back-link" to="/equipment"><ArrowLeft size={16} /> Voltar para equipamentos</Link><div className="details-heading"><div className="profile-heading"><div className="profile-avatar equipment-avatar"><Laptop size={24} /></div><div><p className="eyebrow">Ficha do equipamento</p><h2>{title}</h2><p className="muted">{item.type} · cadastrado em {new Intl.DateTimeFormat('pt-BR').format(new Date(item.createdAt))}</p></div></div><div className="heading-actions"><Link className="button button-secondary" to={`/equipment/${id}/edit`}><Edit3 size={16} /> Editar</Link><button className="button button-danger-outline" type="button" onClick={() => setConfirm(true)}><Trash2 size={16} /> Excluir</button></div></div><div className="details-grid"><Card><div className="section-heading"><h3>Dados do equipamento</h3></div><div className="info-list"><div><Tag size={16} /><span><small>Tipo</small>{item.type}</span></div><div><Laptop size={16} /><span><small>Marca e modelo</small>{[item.brand, item.model].filter(Boolean).join(' ') || 'Não informado'}</span></div><div><Hash size={16} /><span><small>Número de série</small>{item.serialNumber || 'Não informado'}</span></div><div><UserRound size={16} /><span><small>Cliente</small><Link className="subtle-link" to={`/customers/${item.customer.id}`}>{item.customer.name}</Link></span></div></div>{item.description ? <div className="notes-block"><small>Descrição</small><p>{item.description}</p></div> : null}</Card><Card><div className="section-heading"><h3>Cliente responsável</h3></div><Link className="customer-callout" to={`/customers/${item.customer.id}`}><div className="profile-avatar profile-avatar-small"><UserRound size={19} /></div><div><strong>{item.customer.name}</strong><span>Ver cadastro do cliente</span></div><ArrowLeft className="rotate-arrow" size={17} /></Link></Card></div><ConfirmDialog isOpen={confirm} title="Excluir equipamento?" message="Essa ação não poderá ser desfeita. Ordens de serviço vinculadas impedem a exclusão." isLoading={deleting} onCancel={() => setConfirm(false)} onConfirm={() => void remove()} />{toast ? <Toast message={toast} onClose={() => setToast('')} /> : null}</div>;
}
