import { useEffect, useState } from 'react';
import { Eye, Pencil, Plus, Trash2, Users } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { customersService } from '../../services/customers';
import type { Customer } from '../../types/customer';
import { ApiError } from '../../services/api';
import { Card } from '../../components/ui/Card';
import { SearchInput } from '../../components/ui/SearchInput';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { Toast } from '../../components/ui/Toast';
import { EmptyState, ErrorState, Loading } from '../../components/ui/ResourceStates';

export function CustomerList() {
  const location = useLocation(); const [customers, setCustomers] = useState<Customer[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Customer | null>(null); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState((location.state as { message?: string } | null)?.message ?? '');
  const load = async () => { setLoading(true); setError(''); try { setCustomers((await customersService.list()).customers); } catch { setError('Não foi possível carregar os clientes.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = customers.filter((customer) => [customer.name, customer.phone, customer.email ?? '', customer.document ?? ''].some((value) => value.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  const remove = async () => { if (!selected) return; setDeleting(true); try { await customersService.remove(selected.id); setCustomers((items) => items.filter((item) => item.id !== selected.id)); setSelected(null); setToast('Cliente excluído com sucesso.'); } catch (cause) { setToast(cause instanceof ApiError && cause.status === 409 ? 'Não é possível excluir este cliente porque existem registros vinculados a ele.' : 'Não foi possível excluir este cliente.'); } finally { setDeleting(false); } };
  return <div className="resource-page"><div className="page-intro"><div><p className="eyebrow">Base de atendimento</p><h2>Clientes</h2><p className="muted">Gerencie os clientes da sua assistência.</p></div><Link className="button button-primary" to="/customers/new"><Plus size={17} /> Novo cliente</Link></div><Card className="resource-card"><div className="resource-toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Buscar cliente por nome, telefone ou email" /><span className="result-count">{filtered.length} {filtered.length === 1 ? 'cliente' : 'clientes'}</span></div>{loading ? <Loading message="Carregando clientes..." /> : error ? <ErrorState message={error} actionLabel="Tentar novamente" onAction={() => void load()} /> : customers.length === 0 ? <EmptyState title="Nenhum cliente encontrado" message="Cadastre o primeiro cliente para começar." actionLabel="Novo cliente" to="/customers/new" /> : filtered.length === 0 ? <div className="inline-empty"><Users size={20} /><p>Nenhum cliente corresponde à busca.</p></div> : <div className="table-wrap"><table className="resource-table"><thead><tr><th>Cliente</th><th>Telefone</th><th>E-mail</th><th className="actions-heading">Ações</th></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id}><td><Link className="resource-name" to={`/customers/${customer.id}`}>{customer.name}</Link></td><td>{customer.phone}</td><td className="muted">{customer.email || 'Não informado'}</td><td><div className="row-actions"><Link className="table-action" to={`/customers/${customer.id}`} aria-label={`Ver ${customer.name}`}><Eye size={16} /></Link><Link className="table-action" to={`/customers/${customer.id}/edit`} aria-label={`Editar ${customer.name}`}><Pencil size={16} /></Link><button className="table-action danger-action" type="button" onClick={() => setSelected(customer)} aria-label={`Excluir ${customer.name}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>}</Card><ConfirmDialog isOpen={selected !== null} title="Excluir cliente?" message="Essa ação não poderá ser desfeita. Clientes com registros vinculados podem não ser removidos." isLoading={deleting} onCancel={() => setSelected(null)} onConfirm={() => void remove()} />{toast ? <Toast message={toast} onClose={() => setToast('')} /> : null}</div>;
}
