import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Edit3, Mail, MapPin, Phone, Plus, Trash2, UserRound } from 'lucide-react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { customersService } from '../../services/customers';
import { equipmentService } from '../../services/equipment';
import type { Customer } from '../../types/customer';
import type { Equipment } from '../../types/equipment';
import { ApiError } from '../../services/api';
import { Card } from '../../components/ui/Card';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { Toast } from '../../components/ui/Toast';
import { ErrorState, Loading } from '../../components/ui/Feedback';

export function CustomerDetails() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [customer, setCustomer] = useState<Customer | null>(null); const [equipment, setEquipment] = useState<Equipment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState((location.state as { message?: string } | null)?.message ?? '');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [customerResponse, equipmentResponse] = await Promise.all([customersService.get(id), equipmentService.list(id)]); setCustomer(customerResponse.customer); setEquipment(equipmentResponse.equipment); } catch (cause) { setError(cause instanceof ApiError && cause.status === 404 ? 'Cliente não encontrado.' : 'Não foi possível carregar os dados do cliente.'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const remove = async () => { setDeleting(true); try { await customersService.remove(id); navigate('/customers', { state: { message: 'Cliente excluído com sucesso.' } }); } catch (cause) { setToast(cause instanceof ApiError && cause.status === 409 ? 'Não é possível excluir este cliente porque existem registros vinculados a ele.' : 'Não foi possível excluir este cliente.'); setConfirm(false); } finally { setDeleting(false); } };
  if (loading) return <Loading message="Carregando cliente..." />; if (error || !customer) return <ErrorState message={error || 'Cliente não encontrado.'} actionLabel="Voltar" onAction={() => navigate('/customers')} />;
  return <div className="details-page"><Link className="back-link" to="/customers"><ArrowLeft size={16} /> Voltar para clientes</Link><div className="details-heading"><div className="profile-heading"><div className="profile-avatar"><UserRound size={24} /></div><div><p className="eyebrow">Perfil do cliente</p><h2>{customer.name}</h2><p className="muted">Cliente desde {new Intl.DateTimeFormat('pt-BR').format(new Date(customer.createdAt))}</p></div></div><div className="heading-actions"><Link className="button button-secondary" to={`/customers/${id}/edit`}><Edit3 size={16} /> Editar</Link><button className="button button-danger-outline" type="button" onClick={() => setConfirm(true)}><Trash2 size={16} /> Excluir</button></div></div><div className="details-grid"><Card><div className="section-heading"><h3>Informações principais</h3></div><div className="info-list"><div><Phone size={16} /><span><small>Telefone</small>{customer.phone}</span></div><div><Mail size={16} /><span><small>E-mail</small>{customer.email || 'Não informado'}</span></div><div><MapPin size={16} /><span><small>Endereço</small>{customer.address || 'Não informado'}</span></div><div><UserRound size={16} /><span><small>CPF/CNPJ</small>{customer.document || 'Não informado'}</span></div></div>{customer.notes ? <div className="notes-block"><small>Observações</small><p>{customer.notes}</p></div> : null}</Card><Card className="related-card"><div className="section-heading"><div><p className="eyebrow">Vínculos</p><h3>Equipamentos</h3></div><Link className="button button-secondary button-small" to={`/equipment/new?customerId=${id}`}><Plus size={15} /> Adicionar</Link></div>{equipment.length === 0 ? <div className="inline-empty"><p>Nenhum equipamento vinculado.</p></div> : <div className="related-list">{equipment.map((item) => <Link to={`/equipment/${item.id}`} className="related-item" key={item.id}><div><strong>{[item.brand, item.model].filter(Boolean).join(' ') || item.type}</strong><span>{item.type}{item.serialNumber ? ` · S/N ${item.serialNumber}` : ''}</span></div><span>Ver detalhes</span></Link>)}</div>}</Card></div><ConfirmDialog isOpen={confirm} title="Excluir cliente?" message="Essa ação não poderá ser desfeita. Clientes com registros vinculados podem não ser removidos." isLoading={deleting} onCancel={() => setConfirm(false)} onConfirm={() => void remove()} />{toast ? <Toast message={toast} onClose={() => setToast('')} /> : null}</div>;
}
