import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { customersService } from '../../services/customers';
import { equipmentService } from '../../services/equipment';
import { serviceOrdersService } from '../../services/service-orders';
import type { Customer } from '../../types/customer';
import type { Equipment } from '../../types/equipment';
import type { ServiceOrderInput } from '../../types/service-order';
import { ApiError } from '../../services/api';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Loading } from '../../components/ui/Feedback';

const emptyForm: ServiceOrderInput = { customerId: '', equipmentId: '', problemDescription: '', technicianNotes: '', estimatedValue: null, finalValue: null };
export function ServiceOrderForm() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [form, setForm] = useState<ServiceOrderInput>(emptyForm); const [customers, setCustomers] = useState<Customer[]>([]); const [equipment, setEquipment] = useState<Equipment[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void (async () => { try { const { customers: loadedCustomers } = await customersService.list(); setCustomers(loadedCustomers); if (id) { const { serviceOrder } = await serviceOrdersService.get(id); setForm({ customerId: serviceOrder.customerId, equipmentId: serviceOrder.equipmentId, problemDescription: serviceOrder.problemDescription, technicianNotes: serviceOrder.technicianNotes ?? '', estimatedValue: serviceOrder.estimatedValue == null ? null : String(serviceOrder.estimatedValue), finalValue: serviceOrder.finalValue == null ? null : String(serviceOrder.finalValue) }); setEquipment((await equipmentService.list(serviceOrder.customerId)).equipment); } } catch (cause) { setError(cause instanceof ApiError && cause.status === 404 ? 'Ordem de serviço não encontrada.' : 'Não foi possível carregar o formulário.'); } finally { setLoading(false); } })(); }, [id]);
  const update = (field: keyof ServiceOrderInput, value: string | null) => setForm((current) => ({ ...current, [field]: value }));
  const selectCustomer = async (customerId: string) => { setForm((current) => ({ ...current, customerId, equipmentId: '' })); setEquipment([]); if (customerId) { try { setEquipment((await equipmentService.list(customerId)).equipment); } catch { setError('Não foi possível carregar os equipamentos deste cliente.'); } } };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.customerId || !form.equipmentId || form.problemDescription.trim().length < 2) { setError('Selecione o cliente, o equipamento e descreva o problema.'); return; } setSaving(true); setError(''); const payload: ServiceOrderInput = { ...form, problemDescription: form.problemDescription.trim(), technicianNotes: form.technicianNotes?.trim() || null, estimatedValue: form.estimatedValue?.trim() || null, finalValue: form.finalValue?.trim() || null }; try { const response = editing && id ? await serviceOrdersService.update(id, payload) : await serviceOrdersService.create(payload); navigate(`/service-orders/${response.serviceOrder.id}`, { state: { message: editing ? 'Ordem de serviço atualizada.' : 'Ordem de serviço criada.' } }); } catch (cause) { setError(cause instanceof ApiError && cause.status === 400 ? 'Revise os campos informados e os valores monetários.' : cause instanceof ApiError && cause.status === 409 ? 'Não foi possível atualizar esta ordem por causa de um conflito.' : 'Não foi possível salvar a ordem de serviço.'); } finally { setSaving(false); } };
  if (loading) return <Loading message="Carregando formulário..." />;
  return <div className="form-page"><Link className="back-link" to={editing && id ? `/service-orders/${id}` : '/service-orders'}><ArrowLeft size={16} /> Voltar para ordens</Link><div className="page-intro compact-intro"><div><p className="eyebrow">Atendimento</p><h2>{editing ? 'Editar ordem de serviço' : 'Nova ordem de serviço'}</h2><p className="muted">Vincule o atendimento ao cliente e ao equipamento correto.</p></div></div><Card className="form-card"><form onSubmit={submit}><div className="form-grid"><label className="full-field">Cliente <span>*</span><select value={form.customerId} onChange={(event) => void selectCustomer(event.target.value)}><option value="">Selecione um cliente</option>{customers.map((customer) => <option value={customer.id} key={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label><label className="full-field">Equipamento <span>*</span><select value={form.equipmentId} onChange={(event) => update('equipmentId', event.target.value)} disabled={!form.customerId}><option value="">{form.customerId ? 'Selecione um equipamento' : 'Selecione primeiro um cliente'}</option>{equipment.map((item) => <option value={item.id} key={item.id}>{[item.brand, item.model].filter(Boolean).join(' ') || item.type}</option>)}</select></label><label className="full-field">Problema relatado <span>*</span><textarea value={form.problemDescription} onChange={(event) => update('problemDescription', event.target.value)} rows={5} placeholder="Descreva o problema informado pelo cliente" /></label><label>Valor estimado<input value={form.estimatedValue ?? ''} onChange={(event) => update('estimatedValue', event.target.value)} inputMode="decimal" placeholder="0,00" /></label><label>Valor final<input value={form.finalValue ?? ''} onChange={(event) => update('finalValue', event.target.value)} inputMode="decimal" placeholder="0,00" /></label><label className="full-field">Observações técnicas<textarea value={form.technicianNotes ?? ''} onChange={(event) => update('technicianNotes', event.target.value)} rows={4} placeholder="Anotações internas da equipe" /></label></div>{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="form-actions"><Link className="button button-secondary" to={editing && id ? `/service-orders/${id}` : '/service-orders'}>Cancelar</Link><Button className="button-primary" type="submit" disabled={saving}><Save size={16} />{saving ? 'Salvando...' : 'Salvar ordem'}</Button></div></form></Card></div>;
}
